#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

# doc: CMD MAJOR_VERSION - Using PGDG, setup postgresql.

pkg_name="postgresql"
pkg_version="${1:-18}"
pkg="${pkg_name}${pkg_version}-server"

tell "Setting up $pkg_name $pkg_version"
if rpm -q pgdg-redhat-repo ; then
  tell "$pkg_name repo already installed."
else
  arch="$(uname -m)"
  major_version="$(rpm -E %{rhel})"
  repo_url="https://download.postgresql.org/pub/repos/yum/reporpms/EL-${major_version}-${arch}/pgdg-redhat-repo-latest.noarch.rpm"
  tell "Installing PGDG repo..."
  sudo dnf install "$repo_url"
fi

if rpm -q "$pkg" ; then
  tell "Already installed: $pkg"
else
  tell "Installing ${pkg}..."
  sudo dnf install "$pkg"
fi

