#!/bin/sh
#
#
set -u -e

for X in "$@"; do
  if test -e "$X"; then
    echo "$X"
    exit 0
  fi
done

err "File not found in: $*"
exit 2

# case "$*" in
# "-h" | "--help")
#   cmd="$(basename "$0")"
#   grep -E '# +doc:' "$0" | sed 's/#[[:space:]]\+doc:// ; s/CMD/'${cmd}'/'
#   ;;
#
# *)
#   echo "!!! Unknown command: $*" >&2
#   exit 1
#   ;;
# esac
